### ISSUE TITLE
Why do you add the config file into the dockeringore file ?

### ISSUE THREAD

**Issue by Silaslacasse** [Nyrrell/tgtg-notifier#5]
I saw that you add the config file in the docker ignore is it normal ? I had to remove it to make it work/

**Comment by Nyrrell** [comment]
The `config.json` file is ignored because I preferred to map the file as a volume in Docker using `-v ./config.json:/usr/app/config.json`

It's a fairly common choice but I'm open to discussion 

https://github.com/Nyrrell/tgtg-notifier?tab=readme-ov-file#run-with-docker
